# Generated by Django 5.1.5 on 2025-02-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='bot1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='bot1_wins',
        ),
        migrations.RemoveField(
            model_name='match',
            name='bot2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='bot2_wins',
        ),
        migrations.RemoveField(
            model_name='testbot',
            name='score',
        ),
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(related_name='matches', to='poker.bot'),
        ),
        migrations.AlterField(
            model_name='match',
            name='total_rounds',
            field=models.IntegerField(default=50),
        ),
    ]
