# Generated by Django 5.1.5 on 2025-02-26 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0002_remove_bot_score_remove_match_bot1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Round',
        ),
    ]
