# Generated by Django 5.1.5 on 2025-02-26 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0003_delete_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='total_chips_exchanged',
        ),
        migrations.RemoveField(
            model_name='match',
            name='total_rounds',
        ),
    ]
