# Generated by Django 5.1 on 2025-02-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poker", "0004_remove_match_total_chips_exchanged_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testmatch",
            old_name="opponent_wins",
            new_name="total_rounds",
        ),
        migrations.AlterField(
            model_name="testmatch",
            name="opponent_name",
            field=models.JSONField(),
        ),
    ]
