# Generated by Django 5.1 on 2025-02-27 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poker", "0006_remove_testmatch_bot1_remove_testmatch_opponent_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testmatch",
            name="bot1",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_bot1",
                to="poker.testbot",
            ),
        ),
        migrations.AlterField(
            model_name="testmatch",
            name="players",
            field=models.ManyToManyField(
                related_name="matches_as_players", to="poker.testbot"
            ),
        ),
    ]
